### PR TITLE
local: Avoid keeping buffer FD opened at all times

### LINKED ISSUE #1111: iio_device_create_buffer() is broken on local
commit aba77ca961414bde29c9856ae3f6797bc6eab9c0 causes `iio_device_create_buffer()` to return `Device or resource busy (16)` when I run it on local.

### PR DESCRIPTION
**Pull request by pcercuei**
The problem of leaving it opened at all times is that other instances of Libiio cannot be ran in parallel.

Fixes #1111.

### CODE REVIEW

**Review by mhennerich — APPROVED** [review]

File: local.c [hunk 1]
```diff
@@ -117,6 +122,10 @@ static void local_shutdown(struct iio_context *ctx)
 			close(dev->pdata->fd);
 		local_free_pdata(dev);
 	}
+
+	if (ctx->pdata && ctx->pdata->lock)
```
Comment (nunojsa) [inline local.c:126]: do we really need the condition?

**Review by nunojsa — APPROVED** [review]
minor comment that likely does not matter

File: local.c (hunk 1 above)
Comment (pcercuei) [reply local.c:126]: Yes, because local_create_context() can fail before the pdata is allocated or the mutex is created. The error path calls iio_context_destroy() which in turn calls local_shutdown().
